# Generated by Django 4.1.1 on 2022-10-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('imageUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('optionName', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('prepaymentPercent', models.IntegerField(default=0)),
                ('hideBuyBtn', models.BooleanField(blank=True, default=True, null=True)),
                ('bonusesPercent', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
