# Generated by Django 4.1.1 on 2022-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_bot',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
